"""add surname

Revision ID: 16595222cd43
Revises: f6eda7049057
Create Date: 2023-03-27 14:07:57.170622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16595222cd43'
down_revision = 'f6eda7049057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), server_default='Иванов', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
